# Generated by Django 4.0.6 on 2022-10-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='age',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
    ]
