# Generated by Django 4.0.6 on 2022-10-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_signup_address_remove_signup_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='name',
        ),
    ]
