# Generated by Django 4.0.6 on 2022-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='confirmpassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
