# Generated by Django 4.0.6 on 2022-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_signup_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
