# Generated by Django 4.0.6 on 2022-11-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='bookanappointment',
            new_name='bookanapointment',
        ),
    ]
