# Generated by Django 4.0.6 on 2022-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
