# Generated by Django 4.0.6 on 2022-11-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_appointment_date_enquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
