# Generated by Django 4.0.6 on 2022-11-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_enquiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='date',
            new_name='datee',
        ),
    ]
