# Generated by Django 4.0.6 on 2022-11-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_date_enquiry_datee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='datee',
            new_name='Dates',
        ),
    ]
