# Generated by Django 4.0.6 on 2022-11-02 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_signup_id_signup_sno_alter_enquiry_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='sno',
        ),
        migrations.AddField(
            model_name='signup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
