# Generated by Django 4.0.6 on 2022-11-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_signup_id_signup_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='Dates',
        ),
    ]
