# Generated by Django 4.0.6 on 2022-11-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_enquiry_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
